### ISSUE TITLE
Invalid CSRF token errro in 1.6.1 while going to query/stack trace tabs

### ISSUE THREAD

**Issue by kkcmadhu** [temporalio/web#258]
Hi the query and terminate button were not working in 1.6.0 hence i upgraded to web 1.6.1
after upgrading to 1.6.1 the query tab appears but it when i try to get a query i get  "invalid CSRF" token error

Pl find attached.

Please note that in this setup , i have  temporal web running in EC2 docker, i do not have Auth configured in temporal-web
but i have an ALB where i do authenticate the user prior to passing the traffic to target group (temporal web) in this case.

![image](https://user-images.githubusercontent.com/997582/107139776-c7c16e00-6943-11eb-94bb-749af61664c2.png)

**Comment by feedmeapples** [comment]
thanks for opening!
The fix is merged, will be part of v1.6.2

**Comment by munir131** [comment]
@feedmeapples Is it fixed for stacktrace tab too?

**Comment by feedmeapples** [comment]
> @feedmeapples Is it fixed for stacktrace tab too?

Yup

**Comment by munir131** [comment]
> > @feedmeapples Is it fixed for stacktrace tab too?
> 
> Yup

Great. Thanks

**Comment by madhukkc** [comment]
hi with 1.6.2 i still see csrf issue, 
i see stack trace not available
i see query tab not being loaded correctly 


![image](https://user-images.githubusercontent.com/73097404/107734207-e13b2f00-6d22-11eb-9f82-4f8b333c762b.png)

**Comment by feedmeapples** [comment]
@madhukkc i'm trying to repro this and always seeing both stack trace and query tabs working
![image](https://user-images.githubusercontent.com/11838981/107802029-b0a0c880-6d15-11eb-8e53-f2eb3fd1b02e.png)

Could you provide more details on reproing. When you open chrome dev tools, do you see `csrf-token` cookie set?
![image](https://user-images.githubusercontent.com/11838981/107802223-e9d93880-6d15-11eb-9d88-82dbd6967767.png)

**Comment by ajaykmis** [comment]
Hi,

I am also running into this issue on v1.6.2 with Chrome. I am trying to Terminate the workflow when I see this issue. One thing though, it works from the Incognito window, so it could be due to some extensions. Let me know if you need any other info? 
Ca
<img width="1784" alt="Screen Shot 2021-02-12 at 2 26 47 PM" src="https://user-images.githubusercontent.com/5490482/107828789-6bdd5780-6d3e-11eb-8c74-b3b244c594e2.png">

**Comment by feedmeapples** [comment]
There were 2 separate issues with CSRF:
 - one related to web's backend middleware not adding CSRF when the app is started from root url (added with `v1.6.2`)
 - another with multiple cookies and accounting for extra space when parsing them (adding in `v1.6.3`)
 Both PRs are checked in. v1.6.3 is on the way

**Comment by feedmeapples** [comment]
Added Unit tests + fixed another corner case when CSRF token was present after csrf-token.sig
https://github.com/temporalio/web/pull/270

**Comment by feedmeapples** [comment]
Please expect the fix with the version `v1.7.0` today

**Comment by madhukkc** [comment]
> @madhukkc i'm trying to repro this and always seeing both stack trace and query tabs working.
> Could you provide more details on reproing. When you open chrome dev tools, do you see `csrf-token` cookie set?
> 
> ![image](https://user-images.githubusercontent.com/11838981/107802029-b0a0c880-6d15-11eb-8e53-f2eb3fd1b02e.png)
> 
> ![image](https://user-images.githubusercontent.com/11838981/107802223-e9d93880-6d15-11eb-9d88-82dbd6967767.png)

I see csrf issues resolved by my quries tab still shows empty.. i use 1.6.3 version of temporal server. I am able to query signal with tctl without issues.. The list of queries still return null from the api call?
Should i fail a separate ticket for that?

**Comment by madhukkc** [comment]
between my query method names are camel cased like getSomeInfo()  and not like connect_state, hope that should not be the problem, it used to work well in 1.5.x

**Comment by madhukkc** [comment]
ok, i think this is a server side/ front end issue (query not working) , web trys to get the query names by raising an exception and parsing the excpetion text and something broke there.

Previously ,i used to see this exception in server side when i go to query tab


`"level":"error","ts":"2021-02-06T14:01:06.842Z","msg":"Uncategorized error","service":"history","wf-namespace-id":"493f72d9-4de5-4e0f-b113-3e37449990fa","wf-id":"feb20210607-worflow","error":"java.lang.IllegalArgumentException: Unknown query type: __cadence_web_list, knownTypes=**[getData, getState]**
`

Now i see 

`"level":"error","ts":"2021-02-18T07:42:13.879Z","msg":"query directly though matching on sticky failed, will not attempt query on non-sticky","service":"history","shard-id":4,"address":"x.y.0.z:7234","shard-item":"0xc0008db680","component":"history-engine","wf-namespace":"dev-cloud","wf-id":"feb20210607-worflow","wf-run-id":"f6786da3-086a-4945-b5c2-f76934731516","wf-query-type":"__cadence_web_list","error":"java.lang.IllegalStateException: Unknown query type: __cadence_web_list\n\tat io.temporal.internal.sync.QueryDispatcher.handleQuery(QueryDispatcher.java:78)\n\tat io.temporal.internal.sync.SyncWorkflowContext.handleQuery(SyncWorkflowContext.java:181)\n\tat io.temporal.internal.sync.WorkflowExecuteRunnable.handleQuery(WorkflowExecuteRunnable.java:76)\n\tat io.temporal.internal.sync.SyncWorkflow.query(SyncWorkflow.java:175)\n\tat io.temporal.internal.replay.ReplayWorkflowExecutor.query(ReplayWorkflowExecutor.java:137)\n\tat io.temporal.internal.replay.ReplayWorkflow`

Possibly thats why my query page is broken this is happening in 1.6.3
